# Generated by Django 3.1 on 2022-04-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kajiyaro_api', '0003_auto_20220426_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housework',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
