# Generated by Django 3.1 on 2022-04-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kajiyaro_api', '0004_auto_20220426_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='housework',
            table='houseworks',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
