# Generated by Django 3.1 on 2022-06-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kajiyaro_api', '0006_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='result_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
