# Generated by Django 3.1 on 2022-06-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kajiyaro_api', '0007_auto_20220612_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
    ]
